// File generated by FlutterFire CLI — run `flutterfire configure` to regenerate.
// IMPORTANT: Replace ALL placeholder values below with your actual Firebase project config.
// To generate correctly: install flutterfire_cli and run `flutterfire configure` in project root.
// See: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Firebase not configured for Linux');
      default:
        throw UnsupportedError('Unsupported platform: $defaultTargetPlatform');
    }
  }

  // ------------------------------------------------------------------
  // Replace these with values from Firebase Console → Project Settings
  // ------------------------------------------------------------------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Ly1MO8mB_c52Mzhis_vEQ8XY9xtw17g',
    appId: '1:685494651118:web:4f7fe1d91ba34cfb344bff',
    messagingSenderId: '685494651118',
    projectId: 'ilandlands',
    authDomain: 'ilandlands.firebaseapp.com',
    storageBucket: 'ilandlands.firebasestorage.app',
    measurementId: 'G-D2508P154N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'CHANGE_ME_ANDROID_API_KEY',
    appId: 'CHANGE_ME_ANDROID_APP_ID',
    messagingSenderId: 'CHANGE_ME_SENDER_ID',
    projectId: 'CHANGE_ME_PROJECT_ID',
    storageBucket: 'CHANGE_ME_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'CHANGE_ME_IOS_API_KEY',
    appId: 'CHANGE_ME_IOS_APP_ID',
    messagingSenderId: 'CHANGE_ME_SENDER_ID',
    projectId: 'CHANGE_ME_PROJECT_ID',
    storageBucket: 'CHANGE_ME_PROJECT_ID.appspot.com',
    iosBundleId: 'com.gulflands.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'CHANGE_ME_MACOS_API_KEY',
    appId: 'CHANGE_ME_MACOS_APP_ID',
    messagingSenderId: 'CHANGE_ME_SENDER_ID',
    projectId: 'CHANGE_ME_PROJECT_ID',
    storageBucket: 'CHANGE_ME_PROJECT_ID.appspot.com',
    iosBundleId: 'com.gulflands.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'CHANGE_ME_WINDOWS_API_KEY',
    appId: 'CHANGE_ME_WINDOWS_APP_ID',
    messagingSenderId: 'CHANGE_ME_SENDER_ID',
    projectId: 'CHANGE_ME_PROJECT_ID',
    storageBucket: 'CHANGE_ME_PROJECT_ID.appspot.com',
  );
}
